consul_node_name: dc1
consul_datacenter_name: home
consul_data_directory: /opt/consul
consul_config_directory: /etc/consul.d
caddyfile_path: /opt/caddy/Caddyfile
consul_dns_port: 8600
consul_http_port: 8500