- name: Provision Ubuntu Template
  hosts: default
  collections:
      - professorsalty.homelab

  pre_tasks:
    - include_role:
        name: add_key
    - include_role:
        name: install_hashicorp_repo
    
- name: Install consul
  become: yes
  package:
    name: consul
    state: present

  tasks:
    - include_role:
        name: install_server_packages
    - include_role:
        name: direct_rsyslog_to_server
    - include_role:
        name: install_netdata
    - include_role:
        name: set_pwdfeedback
        
      # Stagger updates
      # Remember that Ansible's random filter is exclusive
    - name: Set random update time
      set_fact:
        random_upgrade:
          hour: "{{ 6 | random }}"
          minute: "{{ 60 | random }}"
          day: "{{ 7 | random }}"

    - include_role:
        name: jnv.unattended-upgrades
        apply:
          become: yes
        vars:
          unattended_automatic_reboot_time: "{{ random_upgrade.hour }}:{{ random_upgrade.minute }}"
          unattended_update_days: { "{{ random_upgrade.day }}" }
          unattended_automatic_reboot: yes
          unattended_origins_patterns:
            # strings ore interpolated by the role
            # keep the ${ ... } syntax
            - 'origin=Ubuntu,archive=${distro_codename}-security'
            - 'o=Ubuntu,a=${distro_codename}'
            - 'o=Ubuntu,a=${distro_codename}-updates'
            - 'o=Ubuntu,a=${distro_codename}-proposed-updates'

    - include_role:
        name: konstruktoid.hardening
      vars:
        system_upgrade: yes
        packages_blocklist:
          - telnet*
          - tftp*
        sshd_print_motd: no
        sshd_use_dns: yes
    - include_role:
        name: prepare_cloudinit
    - include_role:
        name: remove_netplan
