- name: Setup mediaserver
  hosts: default
  remote_user: toor
  vars:
    job_name: mediaserver
    jellyfin_port: 8096
    airsonic_port: 8080
    calibre_port: 8083
  collections:
      - professorsalty.homelab
      - ansible.community
  tasks:
    - name: Set hostname
      include_role:
        name: set_hostname
      vars:
        hostname: mediaserver

    - name: Mount the drives
      include_role:
        name: create_filesystem
      vars: 
        drives:
          - device: sdb
            mount_point: transcode
            
    - name: Mount samba shares
      include_role:
        name: mount_smb_shares
      vars:
        project_name: "{{ job_name }}"
        smb_credentials:
          - username: mediauser
            password:
            sharepath: media

    - name: Install infrastructure
      include_role:
        name: install_step_cli

    - name: Start the nomad job
      nomad_job:
        host: 
        content: "{{ lookup('file', '{{job_name}}.nomad') }}"
        token:
        state: present
        force_start: yes

    - name: Allow ports 
      include_role:
        name: ufw_allow_ports
      vars:
        configs:
          - service: Jellyfin
            port: "{{jellyfin_port}}"
          - service: Airsonic
            port: "{{airsonic_port}}"
          - service: CalibreWeb
            port: "{{calibre_port}}"
